#!/usr/bin/env python3
"""Measure throughput of the CC2530 bandwidth-test firmware via E180 gateway TCP."""

from __future__ import annotations

import argparse
import csv
import json
import socket
import time
from collections import deque
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


FRAME_HEAD = 0x55
UPLINK_TYPE = 0x82
ZCL_COMMAND = 0x0F
BANDWIDTH_MARKER = 0xB0
BANDWIDTH_VERSION = 0x02


def iso_now() -> str:
    return datetime.now().astimezone().isoformat(timespec="milliseconds")


def xor_checksum(data: bytes) -> int:
    value = 0
    for byte in data:
        value ^= byte
    return value


def signed_u8(value: int) -> int:
    return value - 256 if value >= 128 else value


def extract_frames(buffer: bytearray):
    while True:
        try:
            head = buffer.index(FRAME_HEAD)
        except ValueError:
            buffer.clear()
            return
        if head:
            del buffer[:head]
        if len(buffer) < 2:
            return
        total_length = buffer[1] + 2
        if total_length < 5 or total_length > 255:
            del buffer[0]
            continue
        if len(buffer) < total_length:
            return
        frame = bytes(buffer[:total_length])
        del buffer[:total_length]
        yield frame


@dataclass
class DeviceStats:
    address: str
    stage: int
    period_ms: int
    first_time: float | None = None
    last_time: float | None = None
    first_rejected: int | None = None
    last_rejected: int | None = None
    first_sequence: int | None = None
    last_sequence: int | None = None
    received_frames: int = 0
    application_bytes: int = 0
    gateway_bytes: int = 0
    missing_frames: int = 0
    duplicate_frames: int = 0
    out_of_order_frames: int = 0
    checksum_errors: int = 0
    rssi_sum: int = 0
    rssi_count: int = 0

    def record_sequence(self, sequence: int) -> None:
        if self.first_sequence is None:
            self.first_sequence = sequence
            self.last_sequence = sequence
            return

        assert self.last_sequence is not None
        delta = (sequence - self.last_sequence) & 0xFFFFFFFF
        if delta == 0:
            self.duplicate_frames += 1
        elif delta < 0x80000000:
            if delta > 1:
                self.missing_frames += delta - 1
            self.last_sequence = sequence
        else:
            self.out_of_order_frames += 1


def parse_bandwidth_frame(frame: bytes):
    if len(frame) < 28:
        return None
    if frame[2] != UPLINK_TYPE or frame[3] != ZCL_COMMAND:
        return None
    if xor_checksum(frame[2:-1]) != frame[-1]:
        return {"checksum_valid": False}

    short_address = f"0x{frame[6]:02X}{frame[5]:02X}"
    endpoint = frame[7]
    cluster_id = frame[10] | (frame[11] << 8)
    rssi_dbm = signed_u8(frame[14])

    # The gateway removes the five-byte ZCL header generated by the terminal.
    payload = frame[16:-1]
    if len(payload) < 11:
        return None
    if payload[0] != BANDWIDTH_MARKER or payload[1] not in (0x01, 0x02):
        return None

    version = payload[1]
    if version == 0x02:
        if len(payload) < 14:
            return None
        stage = payload[3]
        period_ms = int.from_bytes(payload[4:6], "little")
        sequence = int.from_bytes(payload[6:10], "little")
        accepted = int.from_bytes(payload[10:12], "little")
        rejected = int.from_bytes(payload[12:14], "little")
    else:
        stage = 0
        period_ms = 1000
        sequence = int.from_bytes(payload[3:7], "little")
        accepted = int.from_bytes(payload[7:9], "little")
        rejected = int.from_bytes(payload[9:11], "little")
    return {
        "checksum_valid": True,
        "short_address": short_address,
        "endpoint": endpoint,
        "cluster_id": cluster_id,
        "rssi_dbm": rssi_dbm,
        "terminal_id": payload[2],
        "stage": stage,
        "period_ms": period_ms,
        "sequence": sequence,
        "accepted_count": accepted,
        "rejected_count": rejected,
        "application_length": len(payload),
    }


def run(args) -> int:
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_path = output_dir / f"bandwidth_frames_{stamp}.csv"
    summary_path = output_dir / f"bandwidth_summary_{stamp}.json"

    expected = args.expected_short.upper()
    stats: dict[tuple[str, int], DeviceStats] = {}
    buffer = bytearray()
    recent = deque()
    peak_gateway_bps = 0.0
    peak_application_bps = 0.0
    total_tcp_bytes = 0
    valid_test_frames = 0
    start = time.monotonic()
    last_valid = start

    with csv_path.open("w", newline="", encoding="utf-8-sig") as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=[
                "timestamp",
                "short_address",
                "terminal_id",
                "stage",
                "period_ms",
                "sequence",
                "accepted_count",
                "rejected_count",
                "application_length",
                "gateway_frame_length",
                "rssi_dbm",
            ],
        )
        writer.writeheader()

        print(f"连接网关 {args.host}:{args.port} ...")
        with socket.create_connection((args.host, args.port), timeout=5) as sock:
            sock.settimeout(1.0)
            print(
                f"已连接，监听 {args.duration:.0f} 秒；"
                f"目标短地址 {args.expected_short}。按 Ctrl+C 可提前结束。"
            )
            try:
                while time.monotonic() - start < args.duration:
                    try:
                        chunk = sock.recv(4096)
                    except socket.timeout:
                        if time.monotonic() - last_valid > args.idle_timeout:
                            print(f"连续 {args.idle_timeout:.0f} 秒没有带宽测试帧，停止测试。")
                            break
                        continue
                    if not chunk:
                        print("网关关闭了TCP连接。")
                        break
                    total_tcp_bytes += len(chunk)
                    buffer.extend(chunk)

                    for frame in extract_frames(buffer):
                        parsed = parse_bandwidth_frame(frame)
                        if not parsed:
                            continue
                        if not parsed["checksum_valid"]:
                            continue
                        if expected and parsed["short_address"].upper() != expected:
                            continue

                        now = time.monotonic()
                        last_valid = now
                        valid_test_frames += 1
                        address = parsed["short_address"]
                        stats_key = (address, parsed["stage"])
                        device = stats.setdefault(
                            stats_key,
                            DeviceStats(
                                address,
                                parsed["stage"],
                                parsed["period_ms"],
                            ),
                        )
                        if device.first_time is None:
                            device.first_time = now
                            device.first_rejected = parsed["rejected_count"]
                        device.last_time = now
                        device.last_rejected = parsed["rejected_count"]
                        device.received_frames += 1
                        device.application_bytes += parsed["application_length"]
                        device.gateway_bytes += len(frame)
                        device.rssi_sum += parsed["rssi_dbm"]
                        device.rssi_count += 1
                        device.record_sequence(parsed["sequence"])

                        writer.writerow(
                            {
                                "timestamp": iso_now(),
                                "short_address": address,
                                "terminal_id": parsed["terminal_id"],
                                "stage": parsed["stage"],
                                "period_ms": parsed["period_ms"],
                                "sequence": parsed["sequence"],
                                "accepted_count": parsed["accepted_count"],
                                "rejected_count": parsed["rejected_count"],
                                "application_length": parsed["application_length"],
                                "gateway_frame_length": len(frame),
                                "rssi_dbm": parsed["rssi_dbm"],
                            }
                        )
                        csv_file.flush()

                        recent.append(
                            (
                                now,
                                parsed["application_length"],
                                len(frame),
                            )
                        )
                        while recent and now - recent[0][0] > args.peak_window:
                            recent.popleft()
                        if recent:
                            window = max(now - recent[0][0], 0.001)
                            app_bps = sum(item[1] for item in recent) * 8 / window
                            gw_bps = sum(item[2] for item in recent) * 8 / window
                            peak_application_bps = max(peak_application_bps, app_bps)
                            peak_gateway_bps = max(peak_gateway_bps, gw_bps)

                        if valid_test_frames % args.print_every == 0:
                            elapsed = now - start
                            print(
                                f"帧={valid_test_frames} "
                                f"阶段={parsed['stage']} "
                                f"周期={parsed['period_ms']}ms "
                                f"SEQ={parsed['sequence']} "
                                f"平均帧率={valid_test_frames / elapsed:.2f}/s "
                                f"RSSI={parsed['rssi_dbm']} dBm"
                            )
            except KeyboardInterrupt:
                print("\n用户停止测试。")

    elapsed = max(time.monotonic() - start, 0.001)
    summaries = []
    for device in stats.values():
        stage_elapsed = max(
            (device.last_time or start) - (device.first_time or start),
            device.period_ms / 1000 if device.period_ms else 0.001,
        )
        expected_frames = device.received_frames + device.missing_frames
        loss_rate = (
            device.missing_frames * 100 / expected_frames if expected_frames else 0.0
        )
        summaries.append(
            {
                "short_address": device.address,
                "stage": device.stage,
                "period_ms": device.period_ms,
                "elapsed_seconds": round(stage_elapsed, 3),
                "received_frames": device.received_frames,
                "received_fps": round(device.received_frames / stage_elapsed, 3),
                "missing_frames": device.missing_frames,
                "duplicate_frames": device.duplicate_frames,
                "out_of_order_frames": device.out_of_order_frames,
                "loss_rate_percent": round(loss_rate, 4),
                "average_application_bps": round(
                    device.application_bytes * 8 / stage_elapsed, 3
                ),
                "average_gateway_frame_bps": round(
                    device.gateway_bytes * 8 / stage_elapsed, 3
                ),
                "protocol_rejected_delta": (
                    ((device.last_rejected or 0) - (device.first_rejected or 0))
                    & 0xFFFF
                ),
                "average_rssi_dbm": round(
                    device.rssi_sum / device.rssi_count, 2
                )
                if device.rssi_count
                else None,
            }
        )

    stable_stages = [
        item
        for item in summaries
        if item["received_frames"] >= args.minimum_stage_frames
        and item["loss_rate_percent"] < args.maximum_loss_percent
        and item["protocol_rejected_delta"] == 0
        and item["period_ms"] > 0
    ]
    maximum_stable = (
        max(stable_stages, key=lambda item: item["average_application_bps"])
        if stable_stages
        else None
    )

    result = {
        "event": "zigbee_bandwidth_test_complete",
        "timestamp": iso_now(),
        "gateway": {"host": args.host, "port": args.port},
        "duration_seconds": round(elapsed, 3),
        "total_tcp_bytes": total_tcp_bytes,
        "valid_bandwidth_frames": valid_test_frames,
        "peak_window_seconds": args.peak_window,
        "peak_application_bps_observed": round(peak_application_bps, 3),
        "peak_gateway_frame_bps_observed": round(peak_gateway_bps, 3),
        "devices": summaries,
        "maximum_stable_stage": maximum_stable,
        "stability_rule": {
            "maximum_loss_percent": args.maximum_loss_percent,
            "minimum_stage_frames": args.minimum_stage_frames,
            "protocol_rejected_delta": 0,
        },
        "csv_file": str(csv_path),
    }
    summary_path.write_text(
        json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"逐帧记录：{csv_path}")
    print(f"汇总结果：{summary_path}")
    return 0 if valid_test_frames else 2


def main() -> int:
    parser = argparse.ArgumentParser(description="CC2530 Zigbee带宽测试统计程序")
    parser.add_argument("--host", default="192.168.3.7", help="网关IP")
    parser.add_argument("--port", type=int, default=8887, help="网关TCP数据端口")
    parser.add_argument(
        "--expected-short",
        default="0xB25B",
        help="只统计此短地址；传入空字符串可统计所有终端",
    )
    parser.add_argument("--duration", type=float, default=600, help="测试秒数")
    parser.add_argument(
        "--idle-timeout", type=float, default=120, help="无测试帧自动停止秒数"
    )
    parser.add_argument(
        "--peak-window", type=float, default=5, help="峰值滑动窗口秒数"
    )
    parser.add_argument(
        "--print-every", type=int, default=5, help="每收到多少帧打印一次进度"
    )
    parser.add_argument(
        "--maximum-loss-percent",
        type=float,
        default=1.0,
        help="稳定档位允许的最大丢包率",
    )
    parser.add_argument(
        "--minimum-stage-frames",
        type=int,
        default=20,
        help="参与稳定吞吐量判定所需的最少帧数",
    )
    parser.add_argument(
        "--output-dir",
        default=str(Path(__file__).resolve().parent / "bandwidth_results"),
        help="CSV和JSON结果目录",
    )
    return run(parser.parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
